version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-map-gl
    versions:
    - 6.1.0
    - 6.1.1
    - 6.1.10
    - 6.1.11
    - 6.1.2
    - 6.1.3
    - 6.1.4
    - 6.1.5
    - 6.1.6
    - 6.1.7
    - 6.1.8
    - 6.1.9
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: react-scripts
    versions:
    - 4.0.2
