version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Signin to Git
          command: |
            git config --global user.email "danny.phillips8@gmail.com";
            git config --global user.name "Danny Phillips"
      - run:
          name: Setup Dependencies
          command: yarn install
      - run: # run tests
          name: Deploy
          command: yarn run deploy